[package]
name = "rmeter"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true }
fern = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
serde_json = "^1.0.57"
regex = "^1.11"

